import allVerbs from "../verbsDictionary.js"

const dictionary = [ 
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngai", "english": "me, mine"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yo", "english": "you, yours"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ye", "english": "him, her, his, hers"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "biso", "english": "we, ours"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bino", "english": "you, yours"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bango", "english": "them, their"},

  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ananasi", "english": "pineapple"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "awa", "english": "here"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ba", "english": "about"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ba langi", "english": "the colours"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ba mosusu", "english": "the others"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ba travailleurs", "english": "the workers"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "baboti", "english": "parents"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "balabala", "english": "street"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bale", "english": "ball"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "baleinieres", "english": "large boats"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bank", "english": "bank"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "banso", "english": "all"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "batisimu", "english": "baptism"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "batu na maboma", "english": "crazy men"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bendele", "english": "flag"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bile bya ekolo", "english": "homemade"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bilei", "english": "meal"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "biloko", "english": "goods, luggage"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bitabe", "english": "banana"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bitumba", "english": "war"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "boboto", "english": "peace"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokamwi", "english": "surprise"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokei", "english": "departure"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokenzu", "english": "spicy"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokeseni", "english": "difference"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokilo", "english": "brother-in-law"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokilo mobali", "english": "father-in-law"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokilo mwasi", "english": "mother-in-law"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokolongono", "english": "health"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bokono bwa sukali", "english": "diabetes"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bolimbisi", "english": "sorry"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bolingo", "english": "love"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "boloko", "english": "jail"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bololo", "english": "sour"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bolozi", "english": "pain, sore (medical)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bolumbu", "english": "naked"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bondoki", "english": "gun"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bongo", "english": "brain"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bongo", "english": "so far, thus"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "boni", "english": "how"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bopeto", "english": "clean"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "boponi", "english": "choice"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bosoto", "english": "dirty"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "botte", "english": "boot"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "boye", "english": "so, thus"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "brush", "english": "toothbrush"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "bukabuka", "english": "polio"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "butu", "english": "night"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "buuku", "english": "book"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "cadet", "english": "little brother, little sister"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "cafe", "english": "coffee"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "capo", "english": "bonnet (car), hood (car)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "chicwangue", "english": "cassava loaf"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "chocolat", "english": "chocolate"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "cossettes", "english": "cassava chips"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "cuisinair", "english": "chef"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "diaman", "english": "diamond"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "dii", "english": "dear"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "dongodongo", "english": "okra"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "drogadeurs", "english": "informal sector dock workers"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ebale (bibale)", "english": "river(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ebele", "english": "a lot, many"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ebembe (bibembe)", "english": "corpse(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ebende", "english": "iron (metal)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eboto", "english": "descendant, parent"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ebuele (bibuele)", "english": "domestic animal(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ebuteli", "english": "ladder"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "egugi", "english": "rusty"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekange", "english": "hyena"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekeko", "english": "statue"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekesani", "english": "different"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eklezya", "english": "the Church"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekolo", "english": "basket, state"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekolo ya moto", "english": "nationality"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekomeli", "english": "pen"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekoti (bikoti)", "english": "hat(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekoya", "english": "in front of, next"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekuke", "english": "door"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekumbaki", "english": "storm"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ekutu", "english": "pumpkin"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "elanga (bilanga)", "english": "field(s), meadow(s), plantation(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eleki", "english": "behind, past"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "elema", "english": "foolish, mad (insane)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eliki", "english": "desert"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "elikya", "english": "hope"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "elili", "english": "shadow"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eloko", "english": "something"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eloko te", "english": "nothing"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "elongo", "english": "together"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "elozi", "english": "west"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ema", "english": "tent"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "engumba", "english": "city, town"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "enzombo", "english": "pride"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "epesa nzela", "english": "passport"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "epimolo ya sa", "english": "clock"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esaleli", "english": "tools"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esanga", "english": "island"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esende", "english": "squirrel"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esengo (bisengo)", "english": "joy(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esi", "english": "already"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esika (bisika)", "english": "place(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esika esusu", "english": "elsewhere"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esika ya masolo", "english": "sitting room"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "esobe (bisobe)", "english": "forest(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "essence", "english": "petrol"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etalaka", "english": "bridge"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etanda", "english": "bench"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etando", "english": "plain"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eteli", "english": "ripe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eteni", "english": "part (object)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eteyelo", "english": "school"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etima", "english": "lake"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etima moke", "english": "pond"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etuka", "english": "department"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "etumba", "english": "fight"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eyano", "english": "answer"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "eyenga", "english": "festivalF"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "fololo", "english": "flower"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "fufu", "english": "cassava flour"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "fulu", "english": "dustbin, trash can"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "fungola", "english": "key"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "gambala", "english": "fox"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "gillette", "english": "razor"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "goigoi", "english": "lazy"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kabinda", "english": "carpenter"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kabine", "english": "toilet"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kadago", "english": "child soldier"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kala", "english": "old"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kalati", "english": "card"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kanya", "english": "fork"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kasi", "english": "but"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kati", "english": "half"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kati kati", "english": "middle"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ke", "english": "that"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kelasi", "english": "classroom"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kelasi likolo", "english": "university"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ki malu malu", "english": "pick-up truck"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kimia", "english": "peace, peaceful"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kimpuka (bimpuka)", "english": "cassava paste(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kindoki", "english": "sorcery"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kino", "english": "until"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kisi", "english": "medicine"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kisi ya mino", "english": "toothpaste"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kiti", "english": "chair"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kitoko", "english": "beautiful, nice, pretty"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "komba", "english": "broom"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kombo", "english": "name"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "komela", "english": "drink (beverage)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "koni", "english": "firewood"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kopo", "english": "cup"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "koponama", "english": "election"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kuku", "english": "kitchen"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kukulu", "english": "parrot"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kuluna", "english": "criminal"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kuluna en cravate", "english": "white-collar criminal"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kuna", "english": "there"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kunde", "english": "peas"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kuse", "english": "short"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "kwiti", "english": "drunk"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "langi ya mayi ya pondu", "english": "green"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "langi ya motane", "english": "red"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "langi ya mwindu", "english": "black"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "langi ya pembe", "english": "white"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "leki", "english": "younger brother, younger sister"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lelo", "english": "today"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "leta", "english": "government, state"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libala", "english": "marriage"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libanda", "english": "out"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libandi", "english": "bald-headed"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libanga (mabanga)", "english": "pebble(s), stone(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libazi", "english": "lemon"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libela", "english": "permanent"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libelekete", "english": "snail"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libenge (mabenge)", "english": "potato(es)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liboke (maboke)", "english": "fish(es) wrapped in leaves"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libolo", "english": "vagina"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libongo", "english": "beach"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liboso", "english": "front, in front of"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libota", "english": "family"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libulu", "english": "well"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libulu ya mayi", "english": "water well"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libumu", "english": "stomach"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "libumu likangani", "english": "constipation"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lidusu", "english": "hole (in a ruptured pipe)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lifuta", "english": "payment"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likako (makako)", "english": "monkey(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likambo (makambo)", "english": "dispute(s), problem(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likamwisi", "english": "miraculous, wonderful"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likanisi", "english": "idea, thought"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likasa (makasa)", "english": "leaf (leaves)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likata", "english": "penis"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likaya", "english": "cigarette, tobacco"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likei (makei)", "english": "egg(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likelemba", "english": "savings"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likemba (makemba)", "english": "plantain(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likita", "english": "crowd"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likola", "english": "high"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "likolo", "english": "sky, up"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lilala", "english": "orange (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lilita", "english": "cemetery, graveyard"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liloba", "english": "lyrics"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liloki", "english": "magic"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lingisi", "english": "interpreter"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lininisi (maninisi)", "english": "window(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lino (mino)", "english": "tooth (teeth)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lipa", "english": "bread"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lipeka (mapeka)", "english": "shoulder(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lipela", "english": "guava"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisanga", "english": "team"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisango (masango)", "english": "sweet corn, maize"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisano (masano)", "english": "sport(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisano ya motope", "english": "football game"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisanola", "english": "comb, hairbrush"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisasi", "english": "cartridge"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liseke (maseke)", "english": "horn(s) (animal)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liso (miso)", "english": "eye(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisobe", "english": "desert"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lisolo (masolo)", "english": "chat(s), talk(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "litama (matama)", "english": "cheek(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liteya", "english": "lesson"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lititi", "english": "herb"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lititi (matiti)", "english": "grass (lawn)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "litoi (matoi)", "english": "ear(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "litumu", "english": "corner"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "litungulu", "english": "onion"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "litungulu ngenge", "english": "garlic"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "liyebu", "english": "mushroom"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lobi", "english": "tomorrow, yesterday"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "loboko (maboko)", "english": "hand(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "loboko ya mobali", "english": "right"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "loboko ya mwasi", "english": "left"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lobwaku", "english": "valley"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "loko", "english": "deaf"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lokolo", "english": "foot"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lokota (nkota)", "english": "language(s)"}, 
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lokuta", "english": "falsehood, lie"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lola", "english": "heaven, paradise"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lolemo", "english": "tongue"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lolendo", "english": "proud"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lolonge", "english": "manner"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "londende", "english": "fog"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "longwa!", "english": "leave! (confrontational)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lopango", "english": "plot (land)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lopele", "english": "tail (animal)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lopembe", "english": "fog"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "loposo (mposo)", "english": "skin(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "losambo", "english": "prayer"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "loso", "english": "rice"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lupemba", "english": "good luck"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "lutu", "english": "spoon"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mabe", "english": "bad"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mabele", "english": "earth, soil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mabele (libele)", "english": "breast(s), breast milk"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "maboko", "english": "finger(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "maboma", "english": "factory"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "madesu", "english": "beans"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mafuta", "english": "oil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mafuta ya mabila", "english": "clear, cooking oil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mafuta ya nzoi", "english": "honey"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "magazini (bamagazini)", "english": "shop(s), store(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "magazini ya kisi", "english": "pharmacy"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makala", "english": "charcoal"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makasi", "english": "scissors, strong"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makata", "english": "penis and scrotum"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makelele", "english": "noise"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makila", "english": "blood"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makolo", "english": "toe(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "makongi", "english": "fly (insect)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "malamu", "english": "good"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "malasi", "english": "perfume"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "malembe", "english": "slow, slowly"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "malewa", "english": "restaurant"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "malili", "english": "cold, cool, fresh"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mama nkoko", "english": "grandmother"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mambi ya nzambe", "english": "religion"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mami wata", "english": "a female water spirit"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mandefu", "english": "beard"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "maponami", "english": "elections"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "masanga", "english": "alcoholic drink"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "masanga ya sukali", "english": "non-alcoholic drink"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "matabisi", "english": "a tip (restaurant)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "matanga", "english": "funeral, mourning"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mateka", "english": "butter"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "matungana", "english": "boil (cooking)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mawa", "english": "sad"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mayele", "english": "intelligent"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mayi", "english": "water"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mazuti", "english": "diesel"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbakasa", "english": "a foolish, fearful person"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbala", "english": "potato (Kinshasa), sweet potato"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbala", "english": "time (frequency)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbanga", "english": "jaw"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbango", "english": "fast, quick"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbanzi", "english": "bamboo"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbe", "english": "flower"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbeli", "english": "knife"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbeto", "english": "bed"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbila", "english": "palm tree"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbisi", "english": "fish"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mboka", "english": "country, village"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbokatier", "english": "a new, naïve Kinshasa resident"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mboloko", "english": "antelope"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mboma", "english": "yam"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbonge", "english": "wave"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbongo", "english": "money"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbotama", "english": "birth"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbote", "english": "hello"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mboto", "english": "maize"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbu", "english": "ocean, sea"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbula", "english": "rain, year"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbuma", "english": "fruit"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbwa", "english": "dog"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mbwa na nzamba", "english": "fox, wolf"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "meme mobali", "english": "ram"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "meme ya mwasi", "english": "ewe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "meme ya mwana", "english": "lamb"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mesa", "english": "table"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "meta", "english": "waterfall"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mia", "english": "hungry (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mibali", "english": "men"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mikili", "english": "climate"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "miku", "english": "incorrectNumber"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "miliki", "english": "milk"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "milinga", "english": "fire, steam (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mingai", "english": "rheumatism"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mingi", "english": "very"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mingi mingi", "english": "especially"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "minya", "english": "urine"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mive", "english": "tip (restaurant)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mobeko (mibeko)", "english": "law(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mobembo (mibembo)", "english": "holiday(s), trip(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mobimba", "english": "whole"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mobola", "english": "poor (person)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moboti (baboti)", "english": "parent(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mobotisi", "english": "midwife"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moi", "english": "sun"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokambi", "english": "leader"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokanda", "english": "paper"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moke", "english": "few, small"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "Mokili", "english": "Earth"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokima (bakima)", "english": "runner(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokimeli", "english": "refugee"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moko", "english": "each"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokolo", "english": "history, old"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokolo (mikolo)", "english": "day(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokomboso", "english": "chimp, gorilla"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokongeli mokoni", "english": "nurse"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokongo (mikongo)", "english": "back(s) (animal, person)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokoni", "english": "disabled person, patient (hospital)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokoto", "english": "shoe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokulu", "english": "rope"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokuse (mikuse)", "english": "pygmy(ies)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mokuwa (mikuwa)", "english": "bone(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "molakisi", "english": "professor (formal setting), teacher"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "molangi (milangi)", "english": "bottle(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "molinga", "english": "fire, steam"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mololanda", "english": "blind (vision)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "molongo", "english": "the world"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moluka", "english": "stream"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "molunge", "english": "hot"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mombemba", "english": "frog"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mombongo", "english": "a business"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monama", "english": "rainbow"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mondonga", "english": "giraffe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monene", "english": "broad, grand, wide"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mongala", "english": "large stream, small river"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monganga (minganga)", "english": "doctor(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monganga ya banyama", "english": "veterinarian"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mongingo", "english": "voice"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monguna", "english": "enemy"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monili", "english": "electricity"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moninga (baninga)", "english": "friend(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monkalali", "english": "lightning"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monkungi", "english": "mosquito"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monoko (minoko)", "english": "language(s), mouth(s), opening(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monona", "english": "salt"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monuti", "english": "minute (time)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monyele", "english": "east"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monzoto (minzoto)", "english": "star(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "monzuba", "english": "insect sting"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mopanzi", "english": "coast (geology)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mopaya (bapaya)", "english": "foreigner(s), stranger(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mopepe", "english": "wind, air"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosaka mwamba", "english": "less-refined cooking oil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosala (misala)", "english": "work(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosapi (misapi)", "english": "finger(s), toe(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosika", "english": "far"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosisa (misisa)", "english": "vein(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosolo", "english": "dowry"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosopo (misopo)", "english": "intestine(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosuni (misuni)", "english": "flesh, meat(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mosusu", "english": "other"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motako", "english": "copper (metal)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motambola", "english": "walker"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motambuisi (batambuisi)", "english": "driver(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motango", "english": "number"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motema (mitema)", "english": "heart(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motema moto", "english": "an impatient person, heartburn"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moteyi", "english": "pastor (informal setting), teacher"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moto", "english": "fire"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moto (batu)", "english": "human(s), man (men)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moto (mitu)", "english": "head(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moto ya mosala", "english": "work colleague"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motope", "english": "football"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motuka (mituka)", "english": "car(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motuka ya munene", "english": "truck"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motuna (mituna)", "english": "question(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "motuya", "english": "bill (restaurant)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mowuta", "english": "a new, naïve Kinshasa resident"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moyangeli", "english": "deacon"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moye", "english": "heat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moyekeli", "english": "school boy"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moyembi (bayembi)", "english": "singer(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moyi", "english": "day"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "moyibi", "english": "thief"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpakasa", "english": "buffalo"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpasi ya mukongo", "english": "back pain"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpata", "english": "cloud(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpau", "english": "shovel"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpio", "english": "cold"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpiodi", "english": "a type of cheap, imported fish, also called Thompson"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpo", "english": "affair, thing"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpoko", "english": "mouse"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpokwa", "english": "evening"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpondu", "english": "manioc"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mposa", "english": "thirst"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpota", "english": "cut, wound (medical)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpu", "english": "rat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpuku", "english": "rat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mpunda", "english": "donkey, horse"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mputa ya libumu", "english": "haemorrhoids"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mukosa", "english": "itch"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mukuse", "english": "pygmy, short"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mukuwa (mikuwa)", "english": "bone(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mulayi", "english": "tall"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mulunge mabe mpe ketuketu", "english": "influenza"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mulunge", "english": "hot"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mundele (mindele)", "english": "a foreign person, usually white, and usually from Europe, or North America"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mungwa", "english": "salt"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "muselekete (miselekete)", "english": "lizard(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mutuya", "english": "expensive, important, number"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwaa", "english": "few, little, small"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwamba", "english": "palm oil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwamba nguba", "english": "peanut butter"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwana (bana)", "english": "child (children)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwana mwasi", "english": "daughter"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwana ya kelasi", "english": "school boy/school girl"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwana ya mosala", "english": "housekeeper"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwasi (basi)", "english": "wife (wives), woman (women)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwasi ya mokuya", "english": "widow"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwese", "english": "sun"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwete (banzete)", "english": "tree(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "mwinda", "english": "light"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na", "english": "and, in, of, on"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na likolo", "english": "on"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na loboko ya mobali", "english": "on the right"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na loboko ya mwasi", "english": "on the left"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na mbango", "english": "quick, quickly"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na nse", "english": "under"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "na nsima", "english": "next, then"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nainu", "english": "still, yet"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nakati", "english": "in, interior"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nani", "english": "who"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndako", "english": "house"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndako nzambe", "english": "a church"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndako ya bakonzi", "english": "palace"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndambo", "english": "bit, piece"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndeke (bandeke)", "english": "bird(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndeko (bandeko)", "english": "brother(s), sister(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndembo", "english": "rubber"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndenge", "english": "same"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndenge elongobani", "english": "correctNumber, appropriate"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndimo", "english": "orange"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndinga", "english": "language, voice"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndoki", "english": "sorcerer"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndoto", "english": "dream"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nduka", "english": "dam"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndumba", "english": "sex worker"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndunda", "english": "vegetables"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ndunda mobesu", "english": "salad lettuce"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngai moko", "english": "alone"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngana nkisi", "english": "fetish priest"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nganda", "english": "bar (drinking)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngando (bangando)", "english": "crocodile(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngembo", "english": "bat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngembu", "english": "umbrella"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngenge", "english": "poison"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngomba", "english": "mountain"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngomba moke", "english": "hill"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngombe mobali", "english": "bull"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngombe mwasi", "english": "cow"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngonga", "english": "hour"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nguba", "english": "peanuts (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngubu", "english": "hippopotamus"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngulu", "english": "wild boar"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngundeurs", "english": "small-scale rural traders"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ngungutu", "english": "aubergine"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "niama (baniama)", "english": "animal(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "niao", "english": "cat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nionso", "english": "each, every"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkake", "english": "thunder"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkingo", "english": "neck"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkisi", "english": "charms"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkoba", "english": "tortoise"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkoi", "english": "leopard, panther"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkolo", "english": "owner"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkongo", "english": "hoe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nkosi (bankosi)", "english": "lion(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "noki", "english": "immediately"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "noko", "english": "uncle"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nse", "english": "down, low, soil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nsimbiliki na ndako", "english": "rabbit"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nsimbilikil na zamba", "english": "porcupine"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nsongo", "english": "cassava"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nsoso mwasi", "english": "hen"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nsuka", "english": "limit"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ntaba", "english": "goat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ntaba mobali", "english": "billy goat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ntaba mwasi", "english": "nanny goat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ntina", "english": "reason"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ntongo", "english": "dawn, morning"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nyama", "english": "meat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nyama ya mpate", "english": "mutton"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nyama ya ngombe", "english": "beef"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzala", "english": "hunger"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzale", "english": "buffalo"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "Nzambe", "english": "God"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzanga", "english": "midday"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzela ya makolo", "english": "footpath"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzembo", "english": "song"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzete (banzete)", "english": "tree(s) (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzoko", "english": "elephant (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzoku", "english": "elephant"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "nzoto", "english": "body (person)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "osi", "english": "already"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "otele", "english": "hotel"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "oyo", "english": "these, thisP"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pamplemousse", "english": "grapefruit"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pasi", "english": "difficult"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pawuni", "english": "ore"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pe", "english": "and"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pela", "english": "flood"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pembeni", "english": "next to"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "penepene", "english": "very near to"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "penza", "english": "really"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pete", "english": "easy"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pilipili", "english": "pepper"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pitolo", "english": "kerosene, petroleum"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "plafond", "english": "ceiling"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "po", "english": "because"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "po na", "english": "for"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "po na nini", "english": "why"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "polisi", "english": "police"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pompe", "english": "pipe (plumbing)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "poso", "english": "week"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "poto", "english": "Europe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "potopoto", "english": "clay, mud"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pulupulu ya makila", "english": "dysentery"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pulupulu ya nsomo", "english": "cholera"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "pusi", "english": "cat"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "putulu", "english": "ash"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sa", "english": "wristwatch"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sabuni", "english": "soap"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "salite", "english": "dirty"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "samba", "english": "commercially processed cooking oil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sango", "english": "news"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sani (basani)", "english": "plate(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sanse", "english": "luck"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sante", "english": "health"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sanza", "english": "month"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sefu", "english": "chief"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "segonde", "english": "second (time)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sheta", "english": "witch children"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sik’oyo", "english": "now"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sika", "english": "now"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sima", "english": "after, behind"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sima nzanga", "english": "afternoon"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "simisi", "english": "shirt"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sinema", "english": "cinema"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "singa", "english": "string"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "soka", "english": "axe"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "soki", "english": "if"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "solda (basolda)", "english": "soldier(s)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "solo", "english": "small"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sombo", "english": "wild boar"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "soso", "english": "chicken"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sukali", "english": "sugar"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "suki", "english": "hair"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "suku", "english": "room"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "sumuki", "english": "sin"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "supu", "english": "soup"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "susu", "english": "other"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "talatala", "english": "mirror, spectacles"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tangawisi", "english": "ginger"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tango", "english": "time"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tango mosusu", "english": "perhaps"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tata nkoko", "english": "grandfather"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tchaku", "english": "parrot (Kinshasa)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "te", "english": "no, not"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ti", "english": "until"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tikala", "english": "remain"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tike", "english": "ticket"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tiyo", "english": "pipe (plumbing)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "to", "english": "or"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tomati", "english": "tomato"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tongo", "english": "morning"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "tsor", "english": "witch children"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "uta", "english": "from, since"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "vere", "english": "glassW"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "wana", "english": "there (a specific place)"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "wapi", "english": "where"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "wese", "english": "toilet"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "wolo", "english": "gold"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ya", "english": "of"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "ya nani", "english": "whose"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yadi", "english": "yard"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yango", "english": "it, them, they"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yanke", "english": "a strong, courageous person"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yaya", "english": "older brother, older sister"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "Yesu", "english": "Jesus"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yika", "english": "wheel"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yo moko", "english": "yourself"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "yuma", "english": "foolish"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zabolo", "english": "the devil"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zamba", "english": "forest"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zando", "english": "market"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zau", "english": "dustbin, trashcan"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zebi", "english": "science"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zebi za mabanga", "english": "geology"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zebi za mokili", "english": "geography"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zelo", "english": "sand"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zemi", "english": "pregnant"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zoba", "english": "stupid"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zolo", "english": "nose"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zomi", "english": "decade"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zongo", "english": "toilet"},
  {"correctNumber": 0, "incorrectNumber": 0, "lingala": "zuwa", "english": "jealousy"}
].concat(allVerbs);

//allows us to add new words more easily and still keep sorted
const sortDictionary = (currentDictionary, sortBy) => {
  return currentDictionary.concat().sort((a, b) => { return (a[sortBy].toUpperCase() > b[sortBy].toUpperCase() ) ? 1 : ( (a[sortBy].toUpperCase() < b[sortBy].toUpperCase()) ? -1 : 0 ) });
}

const sortedLingalaDictionary = sortDictionary(dictionary, "lingala");

const INITIAL_STATE = {
  "currentDictionary": "lingala",
  "englishDictionary": sortDictionary(dictionary, "english"),
  "testsFinished": 0,
  "showCongratulationsButton": false,
  "miniTest": false,
  "correctNumber": 0,
  "incorrectNumber": 0,
  "numberLearned": 0,
  "dictionary": sortedLingalaDictionary,
  "randomFour": [],
  "testSubject": undefined,
  "currentTestSeries": sortedLingalaDictionary.map((entry, i) => {return i}),
  //has the correctNumber been chosen?,
  "correct": undefined,
  //if chosen, this is the correctNumber index
  "correctIndex": undefined
}

export default INITIAL_STATE;
